@startuml
class com.example.genshinhelper.databinding.DialogInputBinding {
- ConstraintLayout rootView
+ Button inputButton
+ EditText inputCode
+ TextView title
+ ConstraintLayout getRoot()
+ {static} DialogInputBinding inflate(LayoutInflater)
+ {static} DialogInputBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} DialogInputBinding bind(View)
}
class com.example.genshinhelper.databinding.ActivityWeaponBinding {
- ConstraintLayout rootView
+ ConstraintLayout getRoot()
+ {static} ActivityWeaponBinding inflate(LayoutInflater)
+ {static} ActivityWeaponBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ActivityWeaponBinding bind(View)
}
class com.example.genshinhelper.databinding.ActivityCalculatorBinding {
- NestedScrollView rootView
+ ImageView charImage
+ Spinner charSpinner
+ ImageView elementalBurstImg
+ Spinner elementalBurstSpinner
+ ImageView elementalSkillImg
+ Spinner elementalSkillSpinner
+ TextView levelLabel
+ RecyclerView materialsRecycler
+ ImageView normalAttackImg
+ Spinner normalAttackSpinner
+ RecyclerView recyclerBurst
+ RecyclerView recyclerNormalAtk
+ RecyclerView recyclerSkillAtk
+ Slider slider
+ NestedScrollView getRoot()
+ {static} ActivityCalculatorBinding inflate(LayoutInflater)
+ {static} ActivityCalculatorBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ActivityCalculatorBinding bind(View)
}
class com.example.genshinhelper.databinding.ActivityChangeProfileDataBinding {
- ConstraintLayout rootView
+ Button edit
+ EditText emailChange
+ CircleImageView image
+ EditText loginChange
+ EditText passwordTXTChange
+ Button uploadPhoto
+ ConstraintLayout getRoot()
+ {static} ActivityChangeProfileDataBinding inflate(LayoutInflater)
+ {static} ActivityChangeProfileDataBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ActivityChangeProfileDataBinding bind(View)
}
class com.example.genshinhelper.databinding.SkillsCardBinding {
- CardView rootView
+ TextView descriptionSkill
+ ImageView imageSkill
+ TextView nameSkill
+ TextView typeSkill
+ CardView getRoot()
+ {static} SkillsCardBinding inflate(LayoutInflater)
+ {static} SkillsCardBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} SkillsCardBinding bind(View)
}
class com.example.genshinhelper.databinding.FragmentGameItemsBinding {
- FrameLayout rootView
+ TextView logo
+ SearchView search
+ RecyclerView weaponsRecycler
+ FrameLayout getRoot()
+ {static} FragmentGameItemsBinding inflate(LayoutInflater)
+ {static} FragmentGameItemsBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentGameItemsBinding bind(View)
}
class com.example.genshinhelper.databinding.ActivityLoginPageBinding {
- ConstraintLayout rootView
+ ImageView image
+ Button logInButton
+ EditText login
+ EditText password
+ Button regButton
+ TextView text
+ ConstraintLayout getRoot()
+ {static} ActivityLoginPageBinding inflate(LayoutInflater)
+ {static} ActivityLoginPageBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ActivityLoginPageBinding bind(View)
}
class com.example.genshinhelper.databinding.WeaponCharCardBinding {
- CardView rootView
+ TextView atkWeapon
+ ImageView imageWeapon
+ TextView nameWeapon
+ ImageView star
+ TextView substatWeapon
+ CardView getRoot()
+ {static} WeaponCharCardBinding inflate(LayoutInflater)
+ {static} WeaponCharCardBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} WeaponCharCardBinding bind(View)
}
class com.example.genshinhelper.databinding.FragmentCharsBinding {
- NestedScrollView rootView
+ CheckBox anemo
+ CheckBox cryo
+ CheckBox dendro
+ CheckBox electro
+ CheckBox geo
+ CheckBox hydro
+ TextView logo
+ CheckBox pyro
+ RecyclerView recyclerView
+ SearchView search
+ ConstraintLayout sort
+ CheckBox star4
+ CheckBox star5
+ TextView title
+ TextView title2
+ NestedScrollView getRoot()
+ {static} FragmentCharsBinding inflate(LayoutInflater)
+ {static} FragmentCharsBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentCharsBinding bind(View)
}
class com.example.genshinhelper.databinding.ActivityMainBinding {
- ConstraintLayout rootView
+ BottomNavigationView bottomMenu
+ FrameLayout fragment
+ ConstraintLayout getRoot()
+ {static} ActivityMainBinding inflate(LayoutInflater)
+ {static} ActivityMainBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ActivityMainBinding bind(View)
}
class com.example.genshinhelper.databinding.FragmentBlankBinding {
- ConstraintLayout rootView
+ ConstraintLayout getRoot()
+ {static} FragmentBlankBinding inflate(LayoutInflater)
+ {static} FragmentBlankBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentBlankBinding bind(View)
}
class com.example.genshinhelper.databinding.ActivityDetailsWeaponBinding {
- NestedScrollView rootView
+ TextView desc
+ TextView descChar
+ View divider
+ View divider2
+ View divider3
+ ImageView fullImageWeapon
+ TextView fullNameWeapon
+ TextView matTxt
+ RecyclerView materials
+ ImageView stars
+ TextView weaponType
+ NestedScrollView getRoot()
+ {static} ActivityDetailsWeaponBinding inflate(LayoutInflater)
+ {static} ActivityDetailsWeaponBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ActivityDetailsWeaponBinding bind(View)
}
class com.example.genshinhelper.databinding.ActivityLoadingScreenBinding {
- ConstraintLayout rootView
+ ImageView logo
+ ConstraintLayout getRoot()
+ {static} ActivityLoadingScreenBinding inflate(LayoutInflater)
+ {static} ActivityLoadingScreenBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ActivityLoadingScreenBinding bind(View)
}
class com.example.genshinhelper.databinding.FragmentProfileBinding {
- NestedScrollView rootView
+ Button changeProfile
+ TextView email
+ RecyclerView favouriteChars
+ TextView login
+ Button logout
+ CircleImageView profileImage
+ ConstraintLayout profileInfo
+ NestedScrollView getRoot()
+ {static} FragmentProfileBinding inflate(LayoutInflater)
+ {static} FragmentProfileBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentProfileBinding bind(View)
}
class com.example.genshinhelper.databinding.FragmentCharWeaponsBinding {
- NestedScrollView rootView
+ RecyclerView recyclerWeaponChar
+ NestedScrollView getRoot()
+ {static} FragmentCharWeaponsBinding inflate(LayoutInflater)
+ {static} FragmentCharWeaponsBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentCharWeaponsBinding bind(View)
}
class com.example.genshinhelper.databinding.CharsCardBinding {
- CardView rootView
+ ImageView imageChar
+ ImageView imageElement
+ TextView nameCharsText
+ CardView getRoot()
+ {static} CharsCardBinding inflate(LayoutInflater)
+ {static} CharsCardBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} CharsCardBinding bind(View)
}
class com.example.genshinhelper.databinding.ActivityDetailsBinding {
- NestedScrollView rootView
+ TabLayout tabLayout
+ ViewPager2 viewPager2
+ NestedScrollView getRoot()
+ {static} ActivityDetailsBinding inflate(LayoutInflater)
+ {static} ActivityDetailsBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ActivityDetailsBinding bind(View)
}
class com.example.genshinhelper.databinding.MaterialsCharCardBinding {
- CardView rootView
+ ImageView image
+ TextView name
+ TextView quantity
+ CardView getRoot()
+ {static} MaterialsCharCardBinding inflate(LayoutInflater)
+ {static} MaterialsCharCardBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} MaterialsCharCardBinding bind(View)
}
class com.example.genshinhelper.databinding.FragmentMainPageBinding {
- ConstraintLayout rootView
+ Button goToCalculator
+ Button gotoresign
+ RecyclerView talentsDay
+ TextView todayMaterials
+ TextView todayTalents
+ RecyclerView weaponsDay
+ ConstraintLayout getRoot()
+ {static} FragmentMainPageBinding inflate(LayoutInflater)
+ {static} FragmentMainPageBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentMainPageBinding bind(View)
}
class com.example.genshinhelper.databinding.TalentsByDaysMainBinding {
- CardView rootView
+ ImageView imageTalent
+ TextView nameTalentText
+ CardView getRoot()
+ {static} TalentsByDaysMainBinding inflate(LayoutInflater)
+ {static} TalentsByDaysMainBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} TalentsByDaysMainBinding bind(View)
}
class com.example.genshinhelper.databinding.SortingWindowBinding {
- ConstraintLayout rootView
+ CheckBox anemo
+ CheckBox cryo
+ CheckBox dendro
+ CheckBox electro
+ CheckBox geo
+ CheckBox hydro
+ CheckBox pyro
+ TextView title
+ ConstraintLayout getRoot()
+ {static} SortingWindowBinding inflate(LayoutInflater)
+ {static} SortingWindowBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} SortingWindowBinding bind(View)
}
class com.example.genshinhelper.BuildConfig {
+ {static} boolean DEBUG
+ {static} String APPLICATION_ID
+ {static} String BUILD_TYPE
+ {static} int VERSION_CODE
+ {static} String VERSION_NAME
}
class com.example.genshinhelper.databinding.WeaponCardBinding {
- CardView rootView
+ ImageView imageWeapon
+ TextView nameWeapon
+ ImageView star
+ CardView getRoot()
+ {static} WeaponCardBinding inflate(LayoutInflater)
+ {static} WeaponCardBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} WeaponCardBinding bind(View)
}
class com.example.genshinhelper.databinding.ActivityRegisterPageBinding {
- ConstraintLayout rootView
+ EditText confirmPasswordTXT
+ EditText email
+ CircleImageView image
+ EditText login
+ EditText passwordTXT
+ Button regbtn
+ TextView text
+ Button uploadPhoto
+ ConstraintLayout getRoot()
+ {static} ActivityRegisterPageBinding inflate(LayoutInflater)
+ {static} ActivityRegisterPageBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ActivityRegisterPageBinding bind(View)
}
class com.example.genshinhelper.databinding.ActivityTimerResignBinding {
- ConstraintLayout rootView
+ Button btn
+ EditText resign
+ TextView text
+ ConstraintLayout getRoot()
+ {static} ActivityTimerResignBinding inflate(LayoutInflater)
+ {static} ActivityTimerResignBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ActivityTimerResignBinding bind(View)
}
class com.example.genshinhelper.databinding.FragmentMapBinding {
- FrameLayout rootView
+ WebView mapWeb
+ FrameLayout getRoot()
+ {static} FragmentMapBinding inflate(LayoutInflater)
+ {static} FragmentMapBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentMapBinding bind(View)
}
class com.example.genshinhelper.databinding.FragmentCharArtefactsBinding {
- FrameLayout rootView
+ FrameLayout getRoot()
+ {static} FragmentCharArtefactsBinding inflate(LayoutInflater)
+ {static} FragmentCharArtefactsBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentCharArtefactsBinding bind(View)
}
class com.example.genshinhelper.databinding.FragmentDetailsBinding {
- NestedScrollView rootView
+ TextView birthday
+ TextView desc
+ TextView descChar
+ View divider
+ View divider2
+ View divider3
+ View divider4
+ ImageView element
+ ImageView fullImageChar
+ TextView fullName
+ TextView matTxt
+ RecyclerView materials
+ TextView region
+ TextView roleType
+ ImageView star3
+ TextView statsTxt
+ TextView weaponType
+ NestedScrollView getRoot()
+ {static} FragmentDetailsBinding inflate(LayoutInflater)
+ {static} FragmentDetailsBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentDetailsBinding bind(View)
}
class com.example.genshinhelper.databinding.FragmentCharSkillBinding {
- NestedScrollView rootView
+ TextView desc
+ View divider
+ View divider2
+ TextView passive
+ RecyclerView recyclerPassives
+ RecyclerView recyclerSkills
+ NestedScrollView getRoot()
+ {static} FragmentCharSkillBinding inflate(LayoutInflater)
+ {static} FragmentCharSkillBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentCharSkillBinding bind(View)
}


androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.DialogInputBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.ActivityWeaponBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.ActivityCalculatorBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.ActivityChangeProfileDataBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.SkillsCardBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.FragmentGameItemsBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.ActivityLoginPageBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.WeaponCharCardBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.FragmentCharsBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.ActivityMainBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.FragmentBlankBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.ActivityDetailsWeaponBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.ActivityLoadingScreenBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.FragmentProfileBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.FragmentCharWeaponsBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.CharsCardBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.ActivityDetailsBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.MaterialsCharCardBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.FragmentMainPageBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.TalentsByDaysMainBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.SortingWindowBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.WeaponCardBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.ActivityRegisterPageBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.ActivityTimerResignBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.FragmentMapBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.FragmentCharArtefactsBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.FragmentDetailsBinding
androidx.viewbinding.ViewBinding <|.. com.example.genshinhelper.databinding.FragmentCharSkillBinding
@enduml