package com.example.genshinhelper

import android.content.Context
import com.skydoves.balloon.ArrowPositionRules
import com.skydoves.balloon.Balloon
import com.skydoves.balloon.BalloonAnimation
import com.skydoves.balloon.BalloonSizeSpec

class Tooltips(context: Context) {
    val charsTooltip = Balloon.Builder(context)
        .setWidthRatio(1.0f)
        .setHeight(BalloonSizeSpec.WRAP)
        .setText("Для просмотра персонажей выберите соответствующие галочки")
        .setTextColorResource(R.color.textTooltips)
        .setTextSize(15f)
        .setIconDrawableResource(R.drawable.alhaitam)
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .setArrowSize(10)
        .setArrowPosition(0.1f)
        .setPadding(12)
        .setCornerRadius(8f)
        .setBackgroundColorResource(R.color.tooltips)
        .setBalloonAnimation(BalloonAnimation.FADE)
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .build()
    val searchTooltip = Balloon.Builder(context)
        .setWidthRatio(1.0f)
        .setHeight(BalloonSizeSpec.WRAP)
        .setText("Поиск по имени персонажа")
        .setTextColorResource(R.color.textTooltips)
        .setTextSize(15f)
        .setIconDrawableResource(R.drawable.alhaitam)
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .setArrowSize(10)
        .setArrowPosition(0.1f)
        .setPadding(12)
        .setCornerRadius(8f)
        .setBackgroundColorResource(R.color.tooltips)
        .setBalloonAnimation(BalloonAnimation.FADE)
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .build()
    val weaponsTooltip = Balloon.Builder(context)
        .setWidthRatio(1.0f)
        .setHeight(BalloonSizeSpec.WRAP)
        .setText("Для просмотра подробной информации нажмите на карточку с оружием")
        .setTextColorResource(R.color.textTooltips)
        .setTextSize(15f)
        .setIconDrawableResource(R.drawable.alhaitam)
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .setArrowSize(10)
        .setArrowPosition(0.3f)
        .setPadding(12)
        .setCornerRadius(8f)
        .setBackgroundColorResource(R.color.tooltips)
        .setBalloonAnimation(BalloonAnimation.FADE)
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .build()
    val mainTooltip = Balloon.Builder(context)
        .setWidthRatio(1.0f)
        .setHeight(BalloonSizeSpec.WRAP)
        .setText("Главное меню")
        .setTextColorResource(R.color.textTooltips)
        .setTextSize(15f)
        .setIconDrawableResource(R.drawable.alhaitam)
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .setArrowSize(10)
        .setArrowPosition(0.5f)
        .setPadding(12)
        .setCornerRadius(8f)
        .setBackgroundColorResource(R.color.tooltips)
        .setBalloonAnimation(BalloonAnimation.FADE)
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .build()

    val mapTooltip = Balloon.Builder(context)
        .setWidthRatio(1.0f)
        .setHeight(BalloonSizeSpec.WRAP)
        .setText("Карта игрового мира")
        .setTextColorResource(R.color.textTooltips)
        .setTextSize(15f)
        .setIconDrawableResource(R.drawable.alhaitam)
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .setArrowSize(10)
        .setArrowPosition(0.7f)
        .setPadding(12)
        .setCornerRadius(8f)
        .setBackgroundColorResource(R.color.tooltips)
        .setBalloonAnimation(BalloonAnimation.FADE)
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .build()

    val profileTooltip = Balloon.Builder(context)
        .setWidthRatio(1.0f)
        .setHeight(BalloonSizeSpec.WRAP)
        .setText("Профиль пользователя")
        .setTextColorResource(R.color.textTooltips)
        .setTextSize(15f)
        .setIconDrawableResource(R.drawable.alhaitam)
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .setArrowSize(10)
        .setArrowPosition(0.9f)
        .setPadding(12)
        .setCornerRadius(8f)
        .setBackgroundColorResource(R.color.tooltips)
        .setBalloonAnimation(BalloonAnimation.FADE)
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .build()
    val levelTooltip = Balloon.Builder(context)
        .setWidthRatio(1.0f)
        .setHeight(BalloonSizeSpec.WRAP)
        .setText("Выберите уровень, перемещая ползунок")
        .setTextColorResource(R.color.textTooltips)
        .setTextSize(15f)
        .setIconDrawableResource(R.drawable.alhaitam)
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .setArrowSize(10)
        .setArrowPosition(0.5f)
        .setPadding(12)
        .setCornerRadius(8f)
        .setBackgroundColorResource(R.color.tooltips)
        .setBalloonAnimation(BalloonAnimation.FADE)
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .build()
}